# Time in seconds after which doors will be closed
timeout: 60

# The interval in ticks at which should be checked which doors should be closed
task-timer-interval: 20

# List of doors which should be automatically closed
doors:
- ACACIA_DOOR
- BIRCH_DOOR
- DARK_OAK_DOOR
- JUNGLE_DOOR
- SPRUCE_DOOR
- TRAP_DOOR
- WOODEN_DOOR